language: java
install: ant deps

jdk:
 - oraclejdk9

dist: xenial
language: java
addons:
  apt:
    packages:
      - ant

before_install:
  - cd java
  
script:
  - ant test
 

after_success:
  - bash <(curl -s https://codecov.io/bash)
